### ISSUE TITLE
exposure event and BFO

### ISSUE THREAD

**Issue by diatomsRcool** [CTDbase/exposure-ontology#10]
Please make ExO exposure event a subclass of BFO process. This will bring it in line with OBO Core and will help us with our ECTO development.

**Comment by cjgrondin** [comment]
> Please make ExO exposure event a subclass of BFO process. This will bring it in line with OBO Core and will help us with our ECTO development.
exposure event is currently a top level term for ExO, that aligns with exposure stressor, exposure receptor and exposure outcome. By making exposure event a subclass of BFO process, I'm not sure that adds or clarifies anything for ExO, just changes the top level structure (and consequently it becomes a subclass of occurrent and entity (?) since process is_a occurrent and occurrent is_a entity). Can you please clarify how this will help ECTO development and what are the consequences for ExO?

**Comment by diatomsRcool** [comment]
It would make ExO more reusable by other OBO ontologies by becoming more in line with OBO Core. We would like for ECTO to also be in line with OBO Core because we want it to be reused and incorporated into larger knowledge infrastructures. We would also like to continue to incorporate ExO in ECTO. If ExO does not become OBO Core compliant, then we have to make a decision about whether ECTO becomes compliant or it stops using ExO.
As far as making exposure event a subclass of occurrent and entity I will have to defer to @matentzn. I understand that a thing cannot both be an occurrent and an entity, but I'm a little foggy on where process is_a occurrent and occurrent is_a entity is stated. Is that in BFO? OBO Core?

**Comment by cjgrondin** [comment]
> It would make ExO more reusable by other OBO ontologies by becoming more in line with OBO Core. We would like for ECTO to also be in line with OBO Core because we want it to be reused and incorporated into larger knowledge infrastructures. We would also like to continue to incorporate ExO in ECTO. If ExO does not become OBO Core compliant, then we have to make a decision about whether ECTO becomes compliant or it stops using ExO.
> As far as making exposure event a subclass of occurrent and entity I will have to defer to @matentzn. I understand that a thing cannot both be an occurrent and an entity, but I'm a little foggy on where process is_a occurrent and occurrent is_a entity is stated. Is that in BFO? OBO Core?

I found that in a BFO Tutorial (Barry Smith):
![image](https://user-images.githubusercontent.com/22403969/72162724-776a8c00-3390-11ea-801e-d00ff37f936f.png)
)

**Comment by cjmattin** [comment]
nvm! I see that you are
_______________________________
Carolyn Mattingly, PhD
Professor and Head
University Faculty Scholar
Co-Director, IHSFC, Center for Human Health and the Environment
<http://chhe.research.ncsu.edu/>
North Carolina State University
Department of Biological Sciences
3510 Thomas Hall
Campus Box 7614
Raleigh, NC 27695

Office: (919) 515-1509
Lab: (919) 515-2024
Mattingly Lab website <http://mattinglylab.com/>
Comparative Toxicogenomics Database <http://ctdbase.org/>
*Preferred pronouns: she/her/hers*
<http://ctdbase.org/>

**Comment by diatomsRcool** [comment]
I misspoke earlier. It's ok for a class to be an occurrent and an entity. A class cannot be an occurrent and a continuant. Making ExO exposure event a subclass of BFO process may have one consequence for ExO. If you make exposure event a process it will limit the relationships that can be used for exposure events. For example, you will not be able to say that an exposure is "part of" some material entity. I don't know if you actually use any of these sorts of relationships. If not, then there is no problem. Does that make sense?

**Comment by cjgrondin** [comment]
Ok, doesn't sound like it should be a problem to make Exposure Event a subclass of BFO process

**Comment by cjgrondin** [comment]
Resolved in pull request #12
