### ISSUE TITLE
Broken xref annotation property

### ISSUE THREAD

**Issue by matentzn** [CTDbase/exposure-ontology#11]
The current EXO release contains a broken annotation property that causes issues with old loading pipelines:

```
<owl:AnnotationProperty rdf:about="http://www.geneontology.org/formats/oboInOwl#http://www.geneontology.org/formats/oboInOWL#xref"/>
```

This should be:

```
<owl:AnnotationProperty rdf:about="http://www.geneontology.org/formats/oboInOwl#xref"/>
```

Would you be able to fix that and make a new release?

**Comment by matentzn** [comment]
Correction, the correct annotation property IRI would be:

```
http://www.geneontology.org/formats/oboInOwl#hasDbXref
```

So make sure that neither once of the two 
- http://www.geneontology.org/formats/oboInOwl#http://www.geneontology.org/formats/oboInOWL#xref
- http://www.geneontology.org/formats/oboInOwl#xref

is used.. Thanks!

**Comment by cjgrondin** [comment]
Ok, I'll look into it. Thanks

**Comment by diatomsRcool** [comment]
@cjgrondin what is the status of this?

**Comment by cjgrondin** [comment]
I can not find an annotation with 
http://www.geneontology.org/formats/oboInOwl#http://www.geneontology.org/formats/oboInOWL#xref
in the code at all (under which term was the annotation property?), though it looks like http://www.geneontology.org/formats/oboInOwl#xref 
appears in ExO 83 times in various contexts for different terms.  Can you please be more specific with the issue? Is the broken link every time an annotation property value specifies the IRI http://www.geneontology.org/formats/oboInOwl#xref, and the IRI should now be http://www.geneontology.org/formats/oboInOwl#hasDbXref?  Thanks.

**Comment by matentzn** [comment]
Hey @cjgrondin 

I reworked exo.obo to make it OBO compliant; see here:
https://github.com/CTDbase/exposure-ontology/pull/14

This will fix this here issue and some other; I tried to explain everything in detail in the pull request. If you need help, clarifications or assurances, I am happy to help!

**Comment by cjgrondin** [comment]
Thanks Nico, Can you tell me which tool/software you are using to produce the obo compliant file? I want to investigate the details of why there are differences in the formatting of certain annotations (and whether it's a software or version issue).

**Comment by matentzn** [comment]
To be honest, I mostly use text-editors and ROBOT - I am not an ontology curator, I am an ontology engineer with @dosumis and @cmungall and @jamesoverton and I basically make sure ontologies are logically consistent and are formally correct (and OBO compliant).  

The problem with ExO was, that it was indeed `legal` obo (so you could open it in whatever software), i.e it was not broken in the super strict syntax-parse sense of the word. My assumption is that your issues stem from a weird older version of Protege. OBOEdit or Protege 5.5 should not cause these serialization problems!

My preferred environment is Protege 5.5, but OBO Edit is still in use so.. No problem, I think.  What do you use?

**Comment by cjgrondin** [comment]
I did not create the original ontology, but I believe I used Protege 4.0 to
add terms back in 2017.  I have since downloaded protege 5.5, which should
hopefully be compliant to add new terms.






*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Cynthia J. Grondin, PhDBiocuratorComparative
Toxicogenomics Databasehttp://ctdbase.org <http://ctdbase.org>*

**Comment by matentzn** [comment]
Sounds great! If you need help merging the pull request, or any further help, I am happy to be of assistance :)

**Comment by matentzn** [comment]
So I used a text editor to update the syntax (it would take a month or more to manually do all this) and then used Protege 5.5 to verify that everything was correct; if it helps you, we can have quick Zoom call tomorrow and I will describe everything in more detail :)

**Comment by matentzn** [comment]
I think the syntax error will go away now if you use Protege, because when you select some entity (relation, annotation property) in Protege, it will now only give you the correct ones to chose from! If you use Protege 5.5 you will be fine.

As this is Github, you can also just merge it and make a test; if you dont like it, you can still roll back to the old version! Or call me to sort it out!

**Comment by cjgrondin** [comment]
Ok, I merged it and will roll back if we encounter any issues. Thanks

**Comment by matentzn** [comment]
Great! :) I am here to help!
