### ISSUE TITLE
Proposed label change for exposure stressor

### ISSUE THREAD

**Issue by laurenechan** [CTDbase/exposure-ontology#27]
Hello,
Recently @diatomsRcool has been in contact with a variety of environmental health community members and potential users of ECTO as part of a set of NIEHS workshops focused on language harmonization. Individuals in the community have recommended the use of the term 'exposure stimulus' as opposed to 'exposure stressor' and we propose changing the primary label for ExO:0000000 to 'exposure stimulus' for that reason. 
We hope that changing this label will not only be viewed as more accurate/usable by community users, but that it will also logically align with the OBO Relations Ontology relation 'has exposure stimulus' (RO:0002309), which is currently used in ECTO.

**Comment by cjgrondin** [comment]
I will bring this up for discussion at our next group meeting. In the meantime, I think we should leave this issue open for comments so that community users can weigh any pros/cons of the change and provide feedback before it is implemented. Thanks!

**Comment by cjgrondin** [comment]
Food for thought, definitions from Oxford Languages:
stressor: something that causes a state of strain or tension
stimulus: a thing or event that evokes a specific functional reaction in an organ or tissue

**Comment by cjgrondin** [comment]
Currently, ExO contains 43 instances of 'stressor', including 15 instances of 'exposure_stressor', and 19 instances of 'exposure stressor'. It's possible that some of those occurrences of 'stressor' are preferable to changing them all to 'stimulus'. Please note if any instances of 'stressor' are preferred over 'stimulus' (some may be debatable).

**Comment by cjgrondin** [comment]
@laurenechan @diatomsRcool,  I have opened a pull request that updates 'exposure stressor' label to 'exposure stimulus', as well as related instances of 'stressor' to 'stimulus'. Please let me know if these changes resolve your issue so that I can merge the pull request.

**Comment by matentzn** [comment]
I think given your Oxford dictionary research, you should have two terms. Although I am not quite sure whether perhaps stressor is a subclass of stimulus..

```
stressor: something that causes a state of strain or tension IN A SYSTEM
stimulus: a thing or event that evokes a specific functional reaction IN A SYSTEM
```

If the definitions were more like these above, maybe that would be justified.

**Comment by matentzn** [comment]
(after all pumping money into circulation could be a stimulus for the market right?)

**Comment by cjgrondin** [comment]
I'm copying the last comment from the closed pull request to this thread re: creating new ExO ID for exposure stimulus and whether or not to have exposure stressor be a child term, sibling, or something else.

I think all content discussions are valuable and appreciate all input. My understanding is that exposure stimulus encompasses anything that evokes a response (physical entity, process, mindset) while stressor has a negative impact - strain or tension, suggesting stressor to be a child of stimulus. In any case, I think I should close this pull request and we can move further discussion over to the issue re: relabeling stressor. Perhaps whomever wants the name change should fork the repository and create a pull request and we can discuss further.

**Comment by laurenechan** [comment]
@cjgrondin I've updated the definition to remove 'stimulus' and replaced it with entity. Does that sound ok to you? 

Also regarding the data version and date at the top of the file, could you clarify what you mean? I am not quite sure I know what to adapt in the file. Thank you!

**Comment by cjgrondin** [comment]
'exposure stimulus' term was added, and data-version and date were updated 10/25/2021
