### ISSUE TITLE
Do I need a route?

### ISSUE THREAD

**Issue by diatomsRcool** [CTDbase/exposure-ontology#7]
I have use cases where I need to describe exposure to tropical climates, famine, stress, etc. Would these sorts of exposures have a route?

**Comment by cjgrondin** [comment]
While exposure to tropical climates includes exposure to certain geographical elements as well as weather-related exposures, it's challenging to come up with a single exposure route.
Famine might align with exposure to low socioeconomic status; no route there either
Exposure to stress might depend on the type of stress (physical, mental, etc).  Terms could be added to qualify or describe the exposures, but I can't think of an appropriate route.  Did you have any in mind?

**Comment by diatomsRcool** [comment]
At this point I am not going to specify a route for these things. This may come up in the future, but for now I won't worry about it.
