### ISSUE TITLE
prenatal route

### ISSUE THREAD

**Issue by diatomsRcool** [CTDbase/exposure-ontology#8]
I need a route for describing prenatal exposure. What might that be? Some sort of blood or body fluid exposure route? According to this https://en.wikipedia.org/wiki/Placenta maternal and fetal blood never co-mingle. Perhaps just a "placental" route?

**Comment by cjgrondin** [comment]
Could 'prenatal exposure' cover it without necessarily specifying a route? Some exposure (e.g. radiation) may not occur via the placenta.  Many exposure studies measure biomarkers in fetal blood and maternal blood at time of birth.

**Comment by diatomsRcool** [comment]
Yes, it's possible. Is prenatal exposure already in ExO? I can't find it in ontobee.

**Comment by cjgrondin** [comment]
grad student working on this and it's not relevant for this ontology

**Comment by diatomsRcool** [comment]
Actually, can we reopen this? I think we would like to add "maternal" route. That would cover a wide spectrum of things.

**Comment by laurenechan** [comment]
Some of our upcoming use cases are depicting a need to describe exposures to a fetus that would be via the mother. An example of such as an 'exposure to ethanol' impacting the fetus via a 'maternal' route, which would indicate the mother had an 'exposure to ethanol' via 'ingestion' and the fetus experienced the ethanol via their mother's exposure. 

We may need to clarify if the use cases for this route would only include transmission or absorption of substances from mom to baby via a blood/placental type path, or if there would be other 'maternal route' exposures that fall into this realm. Some potentials to consider would be items like:
- Pregnant mother is in a car crash, does the fetus experience direct trauma only? Does the fetus experience trauma via the mother in any facet?
- If mother was to undergo radiation, would the fetus be considered to directly receive the radiation, or is there a maternal "filter" of sorts as the mother's tissue may receive the most of the exposure, keeping the fetus from getting all of it
- If the fetus is experiencing abnormal in utero environment, this could technically related to mom's health status but not a blood related transmission of exposure (i.e. oligohydroaminos, intra-uterine growth restriction)

Should we develop a definition that encompasses any exposure that happens to the fetus, non specific to blood/placenta based transmission?

**Comment by diatomsRcool** [comment]
My instinct is to keep is simple for now and just have the one route, "maternal" that is broad enough for all those use cases.

**Comment by cjgrondin** [comment]
I can create a term 'maternal' as a subclass of route, and would like to add a general definition under annotations, something like 'the transmission of an exposure from pregnant female to fetus'.  Suggestions?

**Comment by diatomsRcool** [comment]
A route by which an exposure to a pregnant female causes an outcome in the fetus that might be observed long after birth
